version: '3'

services:
  db:
    container_name: sregexp-db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "s_regexp"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql:z
      - ./mysql/init:/docker-entrypoint-initdb.d:z
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: s-regexp-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - db
